<DrawerClickableItem@MDNavigationDrawerItem>
    focus_color: "#e7e4c0"
    text_color: "white"
    icon_color: "white"
    ripple_color: "#c5bdd2"
    selected_color: "#0c6c4d"



<Crazy>
    testlabel: testlabel
    MDScreen:
        MDBottomNavigation:
            panel_color: "#292524"
            selected_color_background: "#57534e"
            use_text: False

            MDBottomNavigationItem:
                name: 'scaffold'
                icon: 'ladder'
                badge_icon: "numeric-10"

            MDBottomNavigationItem:
                name: 'camera'
                icon: 'camera'
                badge_icon: "numeric-5"

                MDBoxLayout:
                    orientation: "vertical"
                    MDLabel:
                        id: testlabel
                        text: "Hello World"
                        font_size: 64
                        color: 0, 0, 1, 1

                    MDRectangleFlatButton:
                        text: "Click me"
                        font_size: 32
                        size: 200, 100
                        on_press: root.do_something()

            MDBottomNavigationItem:
                name: 'settings'
                icon: 'cog'
                MDLabel:
                    text: 'Insert settings'
        MDNavigationLayout:


        # Hamburger button + top bar
        MDScreenManager:

            MDScreen:

                MDTopAppBar:

                    pos_hint: {"top": 1}

                    md_bg_color: "#292524"
                    specific_text_color: "white"
                    right_action_items: [["menu", lambda x: nav_drawer.set_state("open")]]

        # Hamburger pop out menu
        MDNavigationDrawer:
            id: nav_drawer
            radius: (16, 0, 0, 16)
            anchor: "right"
            MDNavigationDrawerMenu:
                MDNavigationDrawerHeader:
                    title: "Header title"
                    title_color: "#4a4939"
                    text: "Header text"
                    spacing: "4dp"
                    padding: "12dp", 0, 0, "56dp"

                MDNavigationDrawerLabel:
                    text: "Mail"

                DrawerClickableItem:
                    icon: "gmail"
                    right_text: "+99"
                    text_right_color: "#4a4939"
                    text: "Inbox"

                DrawerClickableItem:
                    icon: "send"
                    text: "Outbox"

                MDNavigationDrawerDivider:

                MDNavigationDrawerLabel:
                    text: "Labels"
